[project]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "mojonn"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
